services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: furia-backend
    ports:
      - "5000:5000"

    environment:
      OLLAMA_URL: "http://ollama:11434"
    restart: unless-stopped

volumes:
  ollama-data:
